#!/bin/bash
set -eou pipefail
echo -n 'step 00-preparation...'
/archinstall/prepare &>/dev/null
echo 'done'
arch-chroot /mnt /archinstall/setup "$@"
rm -rf /mnt/archinstall &>/dev/null
umount -R /mnt &>/dev/null
echo 'Complete! Rebooting'
reboot
