#!/bin/bash
set -eou pipefail
help='Provide the positional arguments [hostname] [ip] [password]'
if [[ -z "${1:-}" ]] || [[ -z "${2:-}" ]] || [[ -z "${3:-}" ]]; then
  echo $help
  exit 1
fi

echo -n 'step 00-preparation...'
/archinstall/prepare &>/dev/null
echo 'done'
arch-chroot /mnt /archinstall/setup "$@"
rm -rf /mnt/archinstall &>/dev/null
umount -R /mnt &>/dev/null
echo 'Complete! Rebooting'
reboot
