#!/bin/bash
set -eou pipefail
read -p "Hostname: " host
read -p "IP: " ip
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/sda
  o # clear the in memory partition table
  n # new partition
  p # primary partition
  1 # partition number 1
    # default - start at beginning of disk 
  +300M # 100 MB boot parttion
  n # new partition
  p # primary partition
  2 # partion number 2
    # default, start immediately after preceding partition
    # default, extend partition to end of disk
  a # make a partition bootable
  1 # bootable partition is partition 1 -- /dev/sda1
  p # print the in-memory partition table
  w # write the partition table
  q # and we're done
EOF
mkfs.fat -F 32 -n boot /dev/sda1
mkfs.ext4 -L arch /dev/sda2
mount /dev/sda2 /mnt
mount --mkdir /dev/sda1 /mnt/boot
reflector --save /etc/pacman.d/mirrorlist --protocol https \
        --latest 5 \
        --sort age \
        --country Australia
pacstrap -K /mnt base base-devel linux linux-firmware git exa fail2ban fzf jq yq man-db man-pages neovim openssh reflector rsync pacman-contrib thefuck tmux ufw unrar unzip wget zoxide nfs-utils ufw pkgfile

genfstab -L /mnt >> /mnt/etc/fstab
cp -r ../archinstall/ /mnt/
arch-chroot /mnt /archinstall/setup $host $ip
exit
rm -rf /mnt/archinstall
umount -R /mnt
reboot
